class HealthRecord {
  int id; // Assuming this is autogenerated on the server side
  int henId;
  int farmId;
  String date;
  String description;

  HealthRecord({
    required this.id,
    required this.henId,
    required this.farmId,
    required this.date,
    required this.description,
  });

  factory HealthRecord.fromJson(Map<String, dynamic> json) {
    return HealthRecord(
      id: json['id'],
      henId: json['hen_id'],
      farmId: json['farm_id'],
      date: json['date'],
      description: json['description'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'hen_id': henId,
      'farm_id': farmId,
      'date': date,
      'description': description,
    };
  }
}
